#pragma once
#include "Module.h"

class Spammer : public IModule {
private:
	int Odelay = 0;
	bool bypass = false;
	bool prefix = true;
	int delay = 2;
	int length = 8;
	int changer = 0;
	std::string message = ">Epsilon Client Owns You and All";
	std::string message2 = ">EZ NN";
	std::string message3 = ">You simply can't beat Epsilon Client";
	std::string message4 = ">You can't beat Epsilon Client";
	std::string message5 = ">I'm the best pvper";
	std::string message6 = ">Keep crying";
	std::string message7 = ">696969696969";
	std::string message8 = ">1v1 or Gay";
	std::string message9 = ">Come to 19k or Gay";
	std::string message10 = ">imagine bypassing";
	std::string message11 = ">Who are you????";
	std::string message12 = ">I'll afk all day so cry about it";
	std::string message13 = ">Join discord.gg/2b2tpeJoin discord.gg/2b2tpeJoin discord.gg/2b2tpeJoin discord.gg/2b2tpe";
	std::string message14 = ">Epsilon Client owns you";
	std::string message15 = ">So bAd";
	std::string message16 = ">Keep coping";
	std::string message17 = ">Epsilon Client destroying famlies since 2022";
	std::string message18 = ">ALL EZZZZZ";
	std::string message19 = ">braindead monkeys";
	std::string message20 = ">Why you still using the s h i t client";
	std::string message21 = ">Join discord.gg/2b2tpe or gonna homeless";
	std::string message22 = ">EZ Owns the server";
	std::string message23 = ">C O P E NN";
	std::string message24 = ">bAd Get A Life sucker UwU";
	std::string message25 = ">Nice iq";
	std::string message26 = ">Quit the game r e t a r d XDDDDDDDDD";
	std::string message27 = ">Best Client LOL keep coping";
	std::string message28 = ">Why is this server so eZ?????";
	std::string message29 = ">NN stop talking";
	std::string message30 = ">hahahahahahah I'll not stop Spam";
	std::string message31 = ">Bypassing your server";
	std::string message32 = ">Cry about You don't have WhiteList";
	std::string message33 = ">L+didnt ask+ez cope nn";
	std::string message34 = ">LoL spam so good";
	std::string message35 = ">Winning all day";
	std::string message36 = ">Stay losing nn";
	std::string message37 = ">I am so Strong";
	std::string message38 = ">Sooooooooooooo bAddddddddddddddddddddddd";
	std::string message39 = ">Get a Good C l i e n t";
	std::string message40 = ">Team DynastY Own ALL";
	std::string message41 = ">Sit down nn";
	std::string message42 = ">DynastY Owns You and All";
	std::string message43 = ">I Win again so eZZZZZZZZ";
	std::string message44 = ">Uninstall or Gay";
	std::string message45 = ">Iq less";
	std::string message46 = ">Where your base go bro";
	std::string message47 = ">I'll easy you in 1sec";
	std::string message48 = ">Keep Losing NN";
	std::string message49 = ">Just quit or keep dying";
	std::string message50 = ">Why you so eZ";
	std::string message51 = ">Your D i c k so small";
	std::string message52 = ">You are so trash uninstall";
	std::string message53 = ">I am the best";
	std::string message54 = ">Iq where";
	std::string message55 = ">Strong hack which fked yr mom";
	std::string message56 = ">Stay ez stay mad stay cope";
	std::string message57 = ">LOL BRAINDEAD SO POOORRR";
	std::string message58 = ">Imagine not being known";
	std::string message59 = ">LOL keep running nn";
	std::string message60 = ">Team DynastY On Top";
	std::string message61 = ">Kys r e t a r d LOL";
	std::string message62 = ">HAHAHAHAHA";
	std::string message63 = ">Client too good?";
	std::string message64 = ">F a g g o t so ezzzzzzzzz";
	std::string message65 = ">Nice iq ";
	std::string message66 = ">Eat s h i t";
	std::string message67 = ">Speedrun LoL";
	std::string message68 = ">Easiest K i l l ever";
	std::string message69 = ">B1tch delete the game plz";
	std::string message70 = ">I am the best";
	std::string message71 = ">I am so much better than you LOL";
	std::string message72 = ">I am the Queen/King LOL";
	std::string message73 = ">Where did your dad go? Qcr";
	std::string message74 = ">Keep barking nn dog";
	std::string message75 = ">Bros so cringe keep dying LOL";
	std::string message76 = ">I am the King/Queen LOL";
	std::string message77 = ">lol k33 why you dont even have own client?";

public:
	Spammer();
	~Spammer();

	inline std::string& getMessage() { return message; };
	inline std::string& getMessage2() { return message2; };
	inline std::string& getMessage3() { return message3; };
	inline std::string& getMessage4() { return message4; };
	inline std::string& getMessage5() { return message5; };
	inline std::string& getMessage6() { return message6; };
	inline std::string& getMessage7() { return message7; };
	inline std::string& getMessage8() { return message8; };
	inline std::string& getMessage9() { return message9; };
	inline std::string& getMessage10() { return message10; };
	inline std::string& getMessage11() { return message11; };
	inline std::string& getMessage12() { return message12; };
	inline std::string& getMessage13() { return message13; };
	inline std::string& getMessage14() { return message14; };
	inline std::string& getMessage15() { return message15; };
	inline std::string& getMessage16() { return message16; };
	inline std::string& getMessage17() { return message17; };
	inline std::string& getMessage18() { return message18; };
	inline std::string& getMessage19() { return message19; };
	inline std::string& getMessage20() { return message20; };
	inline std::string& getMessage21() { return message21; };
	inline std::string& getMessage22() { return message22; };
	inline std::string& getMessage23() { return message23; };
	inline std::string& getMessage24() { return message24; };
	inline std::string& getMessage25() { return message25; };
	inline std::string& getMessage26() { return message26; };
	inline std::string& getMessage27() { return message27; };
	inline std::string& getMessage28() { return message28; };
	inline std::string& getMessage29() { return message29; };
	inline std::string& getMessage30() { return message30; };
	inline std::string& getMessage31() { return message31; };
	inline std::string& getMessage32() { return message32; };
	inline std::string& getMessage33() { return message33; };
	inline std::string& getMessage34() { return message34; };
	inline std::string& getMessage35() { return message35; };
	inline std::string& getMessage36() { return message36; };
	inline std::string& getMessage37() { return message37; };
	inline std::string& getMessage38() { return message38; };
	inline std::string& getMessage39() { return message39; };
	inline std::string& getMessage40() { return message40; };
	inline std::string& getMessage41() { return message41; };
	inline std::string& getMessage42() { return message42; };
	inline std::string& getMessage43() { return message43; };
	inline std::string& getMessage44() { return message44; };
	inline std::string& getMessage45() { return message45; };
	inline std::string& getMessage46() { return message46; };
	inline std::string& getMessage47() { return message47; };
	inline std::string& getMessage48() { return message48; };
	inline std::string& getMessage49() { return message49; };
	inline std::string& getMessage50() { return message50; };
	inline std::string& getMessage51() { return message51; };
	inline std::string& getMessage52() { return message52; };
	inline std::string& getMessage53() { return message53; };
	inline std::string& getMessage54() { return message54; };
	inline std::string& getMessage55() { return message55; };
	inline std::string& getMessage56() { return message56; };
	inline std::string& getMessage57() { return message57; };
	inline std::string& getMessage58() { return message58; };
	inline std::string& getMessage59() { return message59; };
	inline std::string& getMessage60() { return message60; };
	inline std::string& getMessage61() { return message61; };
	inline std::string& getMessage62() { return message62; };
	inline std::string& getMessage63() { return message63; };
	inline std::string& getMessage64() { return message64; };
	inline std::string& getMessage65() { return message65; };
	inline std::string& getMessage66() { return message66; };
	inline std::string& getMessage67() { return message67; };
	inline std::string& getMessage68() { return message68; };
	inline std::string& getMessage69() { return message69; };
	inline std::string& getMessage70() { return message70; };
	inline std::string& getMessage71() { return message71; };
	inline std::string& getMessage72() { return message72; };
	inline std::string& getMessage73() { return message73; };
	inline std::string& getMessage74() { return message74; };
	inline std::string& getMessage75() { return message75; };
	inline std::string& getMessage76() { return message76; };
	inline std::string& getMessage77() { return message77; };

	inline int& getLength() { return length; };
	inline bool& getBypass() { return bypass; };

	// Inherited via IModule
	virtual const char* getModuleName() override;
	virtual const char* getModName() override;
	virtual void onTick(C_GameMode* gm) override;
};